import './globals.css'
import NavBar from './(Components)/NavBar'


export const metadata = {
  title: 'Q NEXT App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <div>
          {children}
        </div>
      </body>
    </html>
  )
}
